/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalOrders' : bigint,
  'revenue' : number,
  'pendingOrders' : bigint,
  'lowStockCount' : bigint,
  'totalCustomers' : bigint,
}
export interface CartItem {
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'price' : number,
}
export interface CustomerView {
  'totalOrders' : bigint,
  'totalSpending' : number,
  'city' : string,
  'name' : string,
  'lastOrderDate' : bigint,
  'email' : string,
  'phone' : string,
}
export interface OrderView {
  'customerName' : string,
  'status' : string,
  'paymentMethod' : string,
  'city' : string,
  'email' : string,
  'orderId' : bigint,
  'cartItems' : Array<CartItem>,
  'state' : string,
  'address' : string,
  'phone' : string,
  'pincode' : string,
}
export interface ProductInventory {
  'productId' : bigint,
  'productName' : string,
  'stock' : bigint,
  'category' : string,
  'price' : number,
}
export interface Review {
  'reviewText' : string,
  'productId' : bigint,
  'reviewerName' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<
    [string, bigint, string, number, bigint],
    undefined
  >,
  'clearCart' : ActorMethod<[string], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllCustomers' : ActorMethod<[], Array<CustomerView>>,
  'getAllOrders' : ActorMethod<[], Array<OrderView>>,
  'getAverageRating' : ActorMethod<[bigint], number>,
  'getCart' : ActorMethod<[string], Array<CartItem>>,
  'getOrder' : ActorMethod<[bigint], [] | [OrderView]>,
  'getProductInventory' : ActorMethod<[], Array<ProductInventory>>,
  'getReviews' : ActorMethod<[bigint], Array<Review>>,
  'getSubscriberCount' : ActorMethod<[], bigint>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    bigint
  >,
  'removeFromCart' : ActorMethod<[string, bigint], undefined>,
  'submitReview' : ActorMethod<[bigint, bigint, string, string], undefined>,
  'subscribe' : ActorMethod<[string], undefined>,
  'updateInventory' : ActorMethod<[bigint, bigint], boolean>,
  'updateOrderStatus' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];