/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdminStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'revenue' : IDL.Float64,
  'pendingOrders' : IDL.Nat,
  'lowStockCount' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
});
export const CustomerView = IDL.Record({
  'totalOrders' : IDL.Nat,
  'totalSpending' : IDL.Float64,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'lastOrderDate' : IDL.Int,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const OrderView = IDL.Record({
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'city' : IDL.Text,
  'email' : IDL.Text,
  'orderId' : IDL.Nat,
  'cartItems' : IDL.Vec(CartItem),
  'state' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const ProductInventory = IDL.Record({
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Review = IDL.Record({
  'reviewText' : IDL.Text,
  'productId' : IDL.Nat,
  'reviewerName' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Float64, IDL.Nat],
      [],
      [],
    ),
  'clearCart' : IDL.Func([IDL.Text], [], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerView)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderView)], ['query']),
  'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'getCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(OrderView)], ['query']),
  'getProductInventory' : IDL.Func([], [IDL.Vec(ProductInventory)], ['query']),
  'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'removeFromCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'submitReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'subscribe' : IDL.Func([IDL.Text], [], []),
  'updateInventory' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdminStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'revenue' : IDL.Float64,
    'pendingOrders' : IDL.Nat,
    'lowStockCount' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
  });
  const CustomerView = IDL.Record({
    'totalOrders' : IDL.Nat,
    'totalSpending' : IDL.Float64,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'lastOrderDate' : IDL.Int,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const OrderView = IDL.Record({
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'city' : IDL.Text,
    'email' : IDL.Text,
    'orderId' : IDL.Nat,
    'cartItems' : IDL.Vec(CartItem),
    'state' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const ProductInventory = IDL.Record({
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Review = IDL.Record({
    'reviewText' : IDL.Text,
    'productId' : IDL.Nat,
    'reviewerName' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Float64, IDL.Nat],
        [],
        [],
      ),
    'clearCart' : IDL.Func([IDL.Text], [], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerView)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderView)], ['query']),
    'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'getCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(OrderView)], ['query']),
    'getProductInventory' : IDL.Func(
        [],
        [IDL.Vec(ProductInventory)],
        ['query'],
      ),
    'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'removeFromCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'submitReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'subscribe' : IDL.Func([IDL.Text], [], []),
    'updateInventory' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };